# ==================== ????? ====================
server.port=8080

# ==================== ????????? ====================
spring.datasource.url=jdbc:mysql://localhost:3306/fi?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==================== MyBatis-Plus ?? ====================
# ??????????? user_name -> userName?
mybatis-plus.configuration.map-underscore-to-camel-case=true
# ????? SQL ????????
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# ??????????
mybatis-plus.global-config.db-config.id-type=auto

mybatis-plus.mapper-locations=classpath*:/mapper/**/*.xml
# ==================== Spring Security ?????? ====================
# ???????????????????????????
spring.security.basic.enabled=false

#????????
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.transaction.support=TRACE
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG